FROM codebox

USER root
RUN POETRY_VIRTUALENVS_CREATE=false poetry install
COPY tests ./tests
RUN ln -s /tmp .pytest_cache; \
    echo '123' > /tmp/try-to-remove.me  # used in tests to check for permissions

USER nobody
